### ISSUE TITLE
Parser issues involving "group" or "on <event>" statements

### ISSUE THREAD

**Issue by 0xaf1f** [jhthorsen/net-isc-dhcpd#26]
I'm trying to identify defined hostnames within a file. Working with the following configuration snippet, I apparently don't detect all the defined hostnames.
Also, printing the parsed configuration does not match the original.

Starting with this file:

```
group {
   filename "fai/pxelinux.0";
   on commit {
        execute("/usr/local/sbin/dhcpd-keytab", host-decl-name);
   }

   host workstation00 {hardware ethernet A1:B2:C3:D4:E5:03; fixed-address 10.1.0.50; ddns-hostname workstation00;}
   host compute00 {hardware ethernet A1:B2:C3:D4:E5:04; fixed-address 10.1.0.154; ddns-hostname compute04;}
   host compute01 {hardware ethernet A1:B2:C3:D4:E5:05; fixed-address 10.1.0.155; ddns-hostname compute05;}
}

group {
   filename "fai/pxelinux.0";
   host diskless00 {hardware ethernet A1:B2:C3:D4:E5:00; fixed-address 10.1.0.246; ddns-hostname diskless00;}
   host diskless01 {hardware ethernet A1:B2:C3:D4:E5:01; fixed-address 10.1.0.247; ddns-hostname diskless01;}
}
```

If I run

``` perl
$dhcpd->config->parse;
print $dhcpd->config->generate;
```

I get:

```
group {
    filename "fai/pxelinux.0";
    on commit {         execute("/usr/local/sbin/dhcpd-keytab", host-decl-name);
}
host workstation00 {
    hardware ethernet A1:B2:C3:D4:E5:03;
    fixed-address 10.1.0.50;
    ddns-hostname workstation00;
}
host compute00 {
    hardware ethernet A1:B2:C3:D4:E5:04;
    fixed-address 10.1.0.154;
    ddns-hostname compute04;
}
host compute01 {
    hardware ethernet A1:B2:C3:D4:E5:05;
    fixed-address 10.1.0.155;
    ddns-hostname compute05;
}
group {
    filename "fai/pxelinux.0";
    host diskless00 {
        hardware ethernet A1:B2:C3:D4:E5:00;
        fixed-address 10.1.0.246;
        ddns-hostname diskless00;
    }
    host diskless01 {
        hardware ethernet A1:B2:C3:D4:E5:01;
        fixed-address 10.1.0.247;
        ddns-hostname diskless01;
    }
}
```

Notice that the second group got nested into the first one, which is not the case in the input file.

I was trying to detect all defined hostnames, but currently, I do not see diskless00 and diskless01--those defined in the second group.

Many thanks for your work on this library!

**Comment by afif-elghraoui** [comment]
If I remove the `on commit` statement, the configuration can be properly regenerated, but then I cannot detect any of the hosts at all. It seems as though groups are not inspected.

**Comment by rfdrake** [comment]
Ok, I've found two problems.  The first is that Group wasn't expecting "on commit" to be under it so it was considering this to be a KeyValue pair and just tripping on itself.

Correcting that, I see that the "on commit" is blank.  I think that's caused by everything being on one line.  I'm betting the "on commit" parser wasn't written with that in mind.

I'm checking to see if I can fix that now.

**Comment by rfdrake** [comment]
This is more difficult than it seems.. actually your bug wasn't too hard to fix and I've corrected it (with an API change), but your test case uncovered another bug that a recent patch added.

    host workstation00 {hardware ethernet A1:B2:C3:D4:E5:03;

The lack of a space between { and "hardware" isn't working anymore.  Rather than revert the new changes, which allow semicolons inside quotes, I've added code to compensate for that which almost works, but it's broken in a couple of strange ways.

I've uploaded the broken code to the "develop" branch just to show my work.  Hopefully I'll come up with a fix soon and can make an alpha release.

**Comment by afif-elghraoui** [comment]
I really appreciate your work on this. However, I'm back to one of my original issues. Ignoring the space issue (I added spaces in for now to avoid that problem), I can't detect any of the defined hosts that are within a `group` block:

```
$dhcpd->config->parse;
foreach my $host ($dhcpd->config->hosts) { print $host->name; }
```

does not print anything. Although the configuration file itself can be successfully reproduced with `$dhcpd->config->generate`. Am I doing something wrong?
